#!/usr/bin/env sh
. ../install
function install
{
    substitute URL with "$URL/public" in application/config/application.php
}
[ "$TARGET" != "" -a "$URL" != "" ]  \
    || die "please specify a TARGET (laravel) directory and your lavarel URL"
copy
install
