#!/usr/bin/env sh
function die
{
    echo $@
    exit 1
}
function substitute
{
    SEP=${SEP:=","}
    sed -i s${SEP}#{$1}${SEP}$3${SEP} "$TARGET/$5" \
        || die "failed substituting $1 with $3 in $5"
}
function install
{
    cp -Lr * $TARGET || die "failed copying to $TARGET"
    substitute URL with "$URL/public" in application/config/application.php
}
[ "$TARGET" != "" -a "$URL" != "" ]  \
    || die "please specify a TARGET (laravel) directory and your lavarel URL"
install
