<?php
return array(
    'url' => '#{URL}',
    'index' => '',
    'key' => '5a01f51272337b45d7400b1772bbf135',
    'encoding' => 'UTF-8',
    'language' => 'en',
    'ssl' => true,
    'timezone' => 'UTC',
    'aliases' => array(
        'Arr'        => 'Laravel\\Arr',
        'Asset'      => 'Laravel\\Asset',
        'Auth'       => 'Laravel\\Auth',
        'Autoloader' => 'Laravel\\Autoloader',
        'Benchmark'  => 'Laravel\\Benchmark',
        'Cache'      => 'Laravel\\Cache\\Manager',
        'Config'     => 'Laravel\\Config',
        'Controller' => 'Laravel\\Routing\\Controller',
        'Cookie'     => 'Laravel\\Cookie',
        'Crypter'    => 'Laravel\\Crypter',
        'DB'         => 'Laravel\\Database\\Manager',
        'Eloquent'   => 'Laravel\\Database\\Eloquent\\Model',
        'File'       => 'Laravel\\File',
        'Form'       => 'Laravel\\Form',
        'Hash'       => 'Laravel\\Hash',
        'HTML'       => 'Laravel\\HTML',
        'Inflector'  => 'Laravel\\Inflector',
        'Input'      => 'Laravel\\Input',
        'IoC'        => 'Laravel\\IoC',
        'Lang'       => 'Laravel\\Lang',
        'Memcached'  => 'Laravel\\Memcached',
        'Paginator'  => 'Laravel\\Paginator',
        'URL'        => 'Laravel\\URL',
        'Redirect'   => 'Laravel\\Redirect',
        'Redis'      => 'Laravel\\Redis',
        'Request'    => 'Laravel\\Request',
        'Response'   => 'Laravel\\Response',
        'Section'    => 'Laravel\\Section',
        'Session'    => 'Laravel\\Facades\\Session',
        'Str'        => 'Laravel\\Str',
        'Validator'  => 'Laravel\\Validator',
        'View'       => 'Laravel\\View',
    ),
);
